# Generated by Django 4.2.16 on 2024-09-12 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Especialidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=8)),
                ('correo_electronico', models.CharField(max_length=100)),
                ('id_especialidades', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Especialidades.especialidades')),
            ],
        ),
    ]
