# Generated by Django 4.2.16 on 2024-09-12 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('diagnostico', models.TextField()),
                ('recomendaciones', models.TextField()),
                ('id_citas', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Citas.citas')),
            ],
        ),
    ]
