# Generated by Django 4.2.15 on 2024-09-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recepcionistas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcionistas',
            name='fecha_ingreso',
            field=models.DateTimeField(),
        ),
    ]
