# Generated by Django 4.2.16 on 2024-09-12 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recepcionistas', '0001_initial'),
        ('Doctores', '0001_initial'),
        ('Pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmacion', models.BooleanField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('id_doctores', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Doctores.doctores')),
                ('id_pacientes', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Pacientes.pacientes')),
                ('id_recepcionistas', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Recepcionistas.recepcionistas')),
            ],
        ),
    ]
