# Generated by Django 4.2.15 on 2024-09-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
    ]
