# Generated by Django 4.2.15 on 2024-09-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='fecha_nacimiento',
            field=models.DateTimeField(),
        ),
    ]
